// <auto-generated />
using System;
using BakTraCam.Core.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BakTraCam.Core.DataAccess.Migrations
{
    [DbContext(typeof(BakTraCamContext))]
    [Migration("20210429200952_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("BakTraCam.Core.Entity.MaintenanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gerceklestiren1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gerceklestiren2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gerceklestiren3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gerceklestiren4")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sorumlu1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sorumlu2")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Maintenance");
                });

            modelBuilder.Entity("BakTraCam.Core.Entity.NoticeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notice");
                });

            modelBuilder.Entity("BakTraCam.Core.Entity.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnvanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BakTraCam.Service.DataContract.MaintenanceModelBasic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gerceklestiren1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gerceklestiren2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gerceklestiren3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gerceklestiren4")
                        .HasColumnType("TEXT");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sorumlu1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sorumlu2")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bakims");
                });

            modelBuilder.Entity("BakTraCam.Service.DataContract.SelectModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.ToView("SelectModel");
                });
#pragma warning restore 612, 618
        }
    }
}
